# Generated by Django 6.0.1 on 2026-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_mattressoption_id_alter_mattressoptionprice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='special_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
