# Generated by Django 6.0.1 on 2026-04-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_productimage_style_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_text', models.CharField(blank=True, default='Coming Soon', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement settings',
                'verbose_name_plural': 'Announcement settings',
            },
        ),
    ]
