# Generated by Django 6.0.1 on 2026-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_product_suggested_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sort_order', '-created_at'], name='prod_cat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'sort_order', '-created_at'], name='prod_subcat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hidden', 'category'], name='prod_hidden_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', 'is_hidden'], name='prod_bestseller_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new', 'is_hidden'], name='prod_new_idx'),
        ),
        migrations.AddIndex(
            model_name='productfiltervalue',
            index=models.Index(fields=['filter_option', 'product'], name='pfv_option_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productfiltervalue',
            index=models.Index(fields=['product', 'filter_option'], name='pfv_product_option_idx'),
        ),
    ]
