# Generated by Django 6.0.1 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmattress",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
