# Generated by Django 6.0.1 on 2026-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_productmattress_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
