# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_order_payment_metadata_order_refund_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
