# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_order_confirmation_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="media",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
