# Generated by Django 6.0.1 on 2026-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_review_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattressoption',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mattressoption',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='targeted_mattress_options', to='api.product'),
        ),
    ]
