# Generated by Django 6.0.1 on 2026-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_mattressoption_display_name_mattressoption_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattressoption',
            name='kids_button_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
