# Generated by Django 6.0.1 on 2026-06-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_category_subcategory_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imported_from_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_copies', to='api.product'),
        ),
    ]
