# Generated by Django 6.0.1 on 2026-06-29 11:03

from django.db import migrations, models


def populate_product_stock_status(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Product.objects.filter(in_stock=True).update(stock_status='available')
    Product.objects.filter(in_stock=False).update(stock_status='out_of_stock')


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_product_imported_from_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('stock_check_needed', 'Stock check needed')], default='', max_length=24),
        ),
        migrations.RunPython(populate_product_stock_status, noop_reverse),
    ]
