# Generated by Django 6.0.1 on 2026-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_productimage_flip_horizontal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoryfilter',
            index=models.Index(fields=['category', 'is_active', 'display_order'], name='cat_filter_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryfilter',
            index=models.Index(fields=['subcategory', 'is_active', 'display_order'], name='cat_filter_sub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryfilter',
            index=models.Index(fields=['filter_type', 'is_active'], name='cat_filter_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hidden', 'subcategory'], name='prod_hidden_subcat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='prod_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['original_price'], name='prod_original_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sort_order'], name='prod_sort_order_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order', 'id'], name='prod_img_product_order_idx'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'price_delta'], name='prod_size_price_idx'),
        ),
    ]
