# Generated by Django 6.0.1 on 2026-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_category_subcategory_discount_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='stock_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of stock'), ('stock_check_needed', 'Stock check needed')], default='available', max_length=24),
        ),
    ]
