# Generated by Django 6.0.1 on 2026-07-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_productcolor_stock_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("out_of_stock", "Out of stock"),
                    ("stock_check_needed", "Stock check needed"),
                ],
                default="available",
                max_length=24,
            ),
        ),
    ]
